apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-claim
spec:
  # 随便写
  storageClassName: renyi
  accessModes:
  #一个pod读写
    - ReadWriteOnce
#多个读，一个写
#    - ReadOnlyMany
#多个读写
#    - ReadWriteMany
  resources:
    requests:
      #1GB
      storage: 1Gi